import { Button } from "@/components/ui/button";
import { Link } from "@tanstack/react-router";
import {
  ArrowRight,
  BrainCircuit,
  Code2,
  Cpu,
  Layers,
  Rocket,
  Terminal,
  Zap,
} from "lucide-react";
import { motion } from "motion/react";

const FEATURES = [
  {
    icon: Terminal,
    title: "Describe Your App",
    description:
      "Type a plain-English prompt. No schema design, no boilerplate — just describe what you want to build.",
  },
  {
    icon: BrainCircuit,
    title: "Get AI Architecture",
    description:
      "Instantly receive a full architecture plan: data models, API surface, and code scaffolding generated by AI.",
  },
  {
    icon: Layers,
    title: "Save Your Ideas",
    description:
      "Every generation is persisted in My Apps. Revisit, refine, and compare multiple architecture variants.",
  },
] as const;

const STEPS = [
  {
    step: "01",
    title: "Type a Prompt",
    detail:
      "Describe your full-stack app in natural language — tech stack, features, and goals.",
  },
  {
    step: "02",
    title: "Get AI Results",
    detail:
      "Review generated Overview, Architecture diagram, and Code Preview tabs with production-ready scaffolding.",
  },
  {
    step: "03",
    title: "Deploy",
    detail:
      "Follow the step-by-step deployment instructions to ship your app on the Internet Computer.",
  },
] as const;

const TECH_TAGS = [
  "Motoko",
  "React",
  "TypeScript",
  "Internet Computer",
  "Groq LLM",
  "Tailwind CSS",
];

export default function Home() {
  return (
    <div className="flex flex-col">
      {/* ── Hero ─────────────────────────────────────────────────── */}
      <section className="bg-background border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-20 sm:py-28 lg:py-36">
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: [0.4, 0, 0.2, 1] }}
            className="max-w-3xl"
          >
            {/* Badge */}
            <div className="inline-flex items-center gap-2 border border-accent/40 bg-accent/10 text-accent px-3 py-1 rounded text-xs font-mono font-medium mb-8 tracking-wide">
              <Zap className="w-3.5 h-3.5" />
              AI-Powered Full-Stack Builder
            </div>

            {/* Headline */}
            <h1 className="font-display font-black text-5xl sm:text-6xl lg:text-7xl tracking-tight text-foreground leading-[1.05] mb-6">
              Build full-stack apps
              <br />
              <span className="text-accent">from a single prompt.</span>
            </h1>

            <p className="font-body text-lg text-muted-foreground max-w-2xl mb-10 leading-relaxed">
              Describe your idea. Synthax generates complete architecture,
              boilerplate code, and deployment instructions — powered by AI,
              running on the Internet Computer.
            </p>

            {/* CTAs */}
            <div className="flex flex-col sm:flex-row items-start gap-3">
              <Link to="/builder" data-ocid="hero-cta-builder">
                <Button
                  size="lg"
                  className="bg-accent hover:bg-accent/90 text-accent-foreground font-mono font-semibold text-sm gap-2 px-6 transition-smooth"
                >
                  <Cpu className="w-4 h-4" />
                  Launch Builder
                  <ArrowRight className="w-4 h-4" />
                </Button>
              </Link>
              <Link to="/my-apps" data-ocid="hero-cta-my-apps">
                <Button
                  variant="outline"
                  size="lg"
                  className="font-mono text-sm gap-2 px-6 border-border hover:border-accent/40 transition-smooth"
                >
                  <Layers className="w-4 h-4" />
                  My Apps
                </Button>
              </Link>
            </div>
          </motion.div>

          {/* Tech tags */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.35, duration: 0.5 }}
            className="mt-14 flex flex-wrap gap-2"
          >
            {TECH_TAGS.map((tag) => (
              <span
                key={tag}
                className="font-mono text-xs text-muted-foreground border border-border px-3 py-1 rounded bg-card"
              >
                {tag}
              </span>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ── Feature Highlights ───────────────────────────────────── */}
      <section className="bg-muted/30 border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.45 }}
            className="mb-12"
          >
            <p className="font-mono text-xs text-accent uppercase tracking-widest mb-2">
              Features
            </p>
            <h2 className="font-display font-black text-3xl sm:text-4xl tracking-tight text-foreground">
              Everything you need to ship.
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 lg:gap-6">
            {FEATURES.map(({ icon: Icon, title, description }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1, duration: 0.4 }}
                className="bg-card border border-border rounded p-6 flex flex-col gap-4 hover:border-accent/40 transition-smooth group"
                data-ocid={`feature-card-${i}`}
              >
                <div className="w-9 h-9 border border-border rounded flex items-center justify-center bg-background group-hover:border-accent/40 group-hover:bg-accent/10 transition-smooth">
                  <Icon className="w-4 h-4 text-muted-foreground group-hover:text-accent transition-colors" />
                </div>
                <div>
                  <h3 className="font-display font-bold text-base text-foreground mb-1.5">
                    {title}
                  </h3>
                  <p className="font-body text-sm text-muted-foreground leading-relaxed">
                    {description}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────── */}
      <section className="bg-background border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.45 }}
            className="mb-12"
          >
            <p className="font-mono text-xs text-accent uppercase tracking-widest mb-2">
              How it works
            </p>
            <h2 className="font-display font-black text-3xl sm:text-4xl tracking-tight text-foreground">
              Three steps to launch.
            </h2>
          </motion.div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-0 border border-border rounded overflow-hidden">
            {STEPS.map(({ step, title, detail }, i) => (
              <motion.div
                key={step}
                initial={{ opacity: 0, x: -12 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.12, duration: 0.4 }}
                className={[
                  "bg-card p-8 flex flex-col gap-3",
                  i < STEPS.length - 1
                    ? "border-b sm:border-b-0 sm:border-r border-border"
                    : "",
                ].join(" ")}
                data-ocid={`step-card-${i}`}
              >
                <span className="font-mono text-4xl font-black text-border select-none">
                  {step}
                </span>
                <div>
                  <h3 className="font-display font-bold text-lg text-foreground mb-1.5">
                    {title}
                  </h3>
                  <p className="font-body text-sm text-muted-foreground leading-relaxed">
                    {detail}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Banner ───────────────────────────────────────────── */}
      <section className="bg-muted/30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-16 sm:py-20">
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.45 }}
            className="border border-border rounded bg-card p-8 sm:p-12 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6"
            data-ocid="cta-banner"
          >
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 bg-accent rounded flex items-center justify-center flex-shrink-0 mt-0.5">
                <Rocket className="w-5 h-5 text-accent-foreground" />
              </div>
              <div>
                <h3 className="font-display font-black text-2xl text-foreground mb-1">
                  Ready to build?
                </h3>
                <p className="font-body text-sm text-muted-foreground max-w-md">
                  Start generating your full-stack app architecture now — no
                  credit card required. Free AI inference via Groq.
                </p>
              </div>
            </div>
            <Link to="/builder" data-ocid="cta-banner-btn">
              <Button
                size="lg"
                className="bg-accent hover:bg-accent/90 text-accent-foreground font-mono font-semibold text-sm gap-2 px-8 flex-shrink-0 transition-smooth"
              >
                <Code2 className="w-4 h-4" />
                Start Building
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
