/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GenerationId = IDL.Nat;
export const Overview = IDL.Record({
  'concept' : IDL.Text,
  'targetUsers' : IDL.Text,
  'keyFeatures' : IDL.Vec(IDL.Text),
});
export const Architecture = IDL.Record({
  'systemDesign' : IDL.Text,
  'dataFlow' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const CodeSnippet = IDL.Record({
  'code' : IDL.Text,
  'filename' : IDL.Text,
});
export const GenerationResult = IDL.Record({
  'overview' : Overview,
  'architecture' : Architecture,
  'codeSnippets' : IDL.Vec(CodeSnippet),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Generation = IDL.Record({
  'id' : GenerationId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'overview' : Overview,
  'architecture' : Architecture,
  'prompt' : IDL.Text,
  'codeSnippets' : IDL.Vec(CodeSnippet),
});
export const GenerationSummary = IDL.Record({
  'id' : GenerationId,
  'createdAt' : Timestamp,
  'promptPreview' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGeneration' : IDL.Func(
      [GenerationId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'generateApp' : IDL.Func([IDL.Text], [GenerationResult], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGeneration' : IDL.Func([GenerationId], [IDL.Opt(Generation)], ['query']),
  'getMyGenerations' : IDL.Func([], [IDL.Vec(GenerationSummary)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGeneration' : IDL.Func(
      [IDL.Text, Overview, Architecture, IDL.Vec(CodeSnippet)],
      [IDL.Variant({ 'ok' : GenerationId, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GenerationId = IDL.Nat;
  const Overview = IDL.Record({
    'concept' : IDL.Text,
    'targetUsers' : IDL.Text,
    'keyFeatures' : IDL.Vec(IDL.Text),
  });
  const Architecture = IDL.Record({
    'systemDesign' : IDL.Text,
    'dataFlow' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const CodeSnippet = IDL.Record({ 'code' : IDL.Text, 'filename' : IDL.Text });
  const GenerationResult = IDL.Record({
    'overview' : Overview,
    'architecture' : Architecture,
    'codeSnippets' : IDL.Vec(CodeSnippet),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Generation = IDL.Record({
    'id' : GenerationId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'overview' : Overview,
    'architecture' : Architecture,
    'prompt' : IDL.Text,
    'codeSnippets' : IDL.Vec(CodeSnippet),
  });
  const GenerationSummary = IDL.Record({
    'id' : GenerationId,
    'createdAt' : Timestamp,
    'promptPreview' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGeneration' : IDL.Func(
        [GenerationId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'generateApp' : IDL.Func([IDL.Text], [GenerationResult], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGeneration' : IDL.Func(
        [GenerationId],
        [IDL.Opt(Generation)],
        ['query'],
      ),
    'getMyGenerations' : IDL.Func([], [IDL.Vec(GenerationSummary)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGeneration' : IDL.Func(
        [IDL.Text, Overview, Architecture, IDL.Vec(CodeSnippet)],
        [IDL.Variant({ 'ok' : GenerationId, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };