/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Architecture {
  'systemDesign' : string,
  'dataFlow' : string,
  'techStack' : Array<string>,
}
export interface CodeSnippet { 'code' : string, 'filename' : string }
export interface Generation {
  'id' : GenerationId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'overview' : Overview,
  'architecture' : Architecture,
  'prompt' : string,
  'codeSnippets' : Array<CodeSnippet>,
}
export type GenerationId = bigint;
export interface GenerationResult {
  'overview' : Overview,
  'architecture' : Architecture,
  'codeSnippets' : Array<CodeSnippet>,
}
export interface GenerationSummary {
  'id' : GenerationId,
  'createdAt' : Timestamp,
  'promptPreview' : string,
}
export interface Overview {
  'concept' : string,
  'targetUsers' : string,
  'keyFeatures' : Array<string>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGeneration' : ActorMethod<
    [GenerationId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'generateApp' : ActorMethod<[string], GenerationResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGeneration' : ActorMethod<[GenerationId], [] | [Generation]>,
  'getMyGenerations' : ActorMethod<[], Array<GenerationSummary>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGeneration' : ActorMethod<
    [string, Overview, Architecture, Array<CodeSnippet>],
    { 'ok' : GenerationId } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];